### ISSUE TITLE
Timeout too small

### ISSUE THREAD

**Issue by essepuntato** [GabrielePisciotta/europe-pubmed-central-dataset#1]
https://github.com/GabrielePisciotta/europe-pubmed-central-dataset/blob/8441a0b98aa0cc2762fc82911aab25d81a3ee3d1/EuropePubMedCentralDataset.py#L505

Set it to 20 since otherwise there is a high probability not to download the links.

**Comment by GabrielePisciotta** [comment]
Changed, thank you
