### ISSUE TITLE
HTTP instead of FTP

### ISSUE THREAD

**Issue by essepuntato** [GabrielePisciotta/europe-pubmed-central-dataset#2]
https://github.com/GabrielePisciotta/europe-pubmed-central-dataset/blob/786b52e990fe79ab42b29e17807f5881e18f10ba/EuropePubMedCentralDataset.py#L115

To change the URL substituting "ftp" with "http", otherwise an error will be generated.

**Comment by GabrielePisciotta** [comment]
Thank you
